
import os
import sqlite3
import pandas as pd
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

DB_PATH = "data/nifty100.db"
OUTPUT_DIR = "reports"

os.makedirs(OUTPUT_DIR, exist_ok=True)

styles = getSampleStyleSheet()

def load_company_data(company_id):
    conn = sqlite3.connect(DB_PATH)

    company = pd.read_sql(
        "SELECT id, company_name FROM companies WHERE id = ?",
        conn,
        params=[company_id],
    )

    ratios = pd.read_sql(
        """
        SELECT *
        FROM financial_ratios
        WHERE company_id = ?
        ORDER BY year DESC
        LIMIT 1
        """,
        conn,
        params=[company_id],
    )

    ranking = pd.read_sql(
        """
        SELECT *
        FROM ranking_engine
        WHERE company_id = ?
        LIMIT 1
        """,
        conn,
        params=[company_id],
    )

    conn.close()

    pros = pd.read_csv("output/pros_cons_generated.csv")
    cash = pd.read_excel("output/cashflow_intelligence.xlsx")
    allocation = pd.read_excel("output/capital_allocation_report.xlsx")

    allocation["company_name"] = (
    allocation["company_name"]
    .astype(str)
    .str.strip()
)

    return (
        company.iloc[0],
        ratios.iloc[0] if not ratios.empty else None,
        ranking.iloc[0] if not ranking.empty else None,
        pros[pros["company_id"] == company_id],
        cash[cash["company_id"] == company_id],
        allocation[
    allocation["company_name"]
    == str(company.iloc[0]["company_name"]).strip()
]
    )

def add_heading(story, text):
    story.append(Paragraph(f"<b>{text}</b>", styles["Heading2"]))
    story.append(Spacer(1, 8))


def generate_pdf(company_id):
    company, ratios, ranking, pros, cash, allocation = load_company_data(company_id)

    filename = os.path.join(
        OUTPUT_DIR,
        f"{company['company_name'].replace('/', '_')}.pdf"
    )

    doc = SimpleDocTemplate(filename)
    story = []

    story.append(Paragraph("<b>Nifty100 Financial Intelligence Platform</b>",
                           styles["Title"]))
    story.append(Spacer(1, 12))

    add_heading(story, "Company Information")
    story.append(Paragraph(f"Company : {company['company_name']}", styles["BodyText"]))

    if ranking is not None:
        rec = ranking["recommendation"] if "recommendation" in ranking else "N/A"
        score = ranking["composite_quality_score"] if "composite_quality_score" in ranking else "N/A"
        story.append(Paragraph(f"Recommendation : {rec}", styles["BodyText"]))
        story.append(Paragraph(f"Quality Score : {score}", styles["BodyText"]))

    story.append(Spacer(1, 12))

    add_heading(story, "Financial Metrics")

    if ratios is not None:
        metrics = [
            ("ROE", "return_on_equity_pct"),
            ("Revenue CAGR", "revenue_cagr_5yr"),
            ("PAT CAGR", "pat_cagr_5yr"),
            ("EPS CAGR", "eps_cagr_5yr"),
            ("Free Cash Flow", "free_cash_flow_cr"),
        ]

        for label, col in metrics:
            if col in ratios.index:
                story.append(
                    Paragraph(f"{label}: {ratios[col]}", styles["BodyText"])
                )

    story.append(Spacer(1, 12))

    add_heading(story, "Pros")
    pro_rows = pros[pros["type"] == "pro"]
    if pro_rows.empty:
        story.append(Paragraph("No major strengths available.", styles["BodyText"]))
    else:
        for _, row in pro_rows.iterrows():
            story.append(Paragraph(f"• {row['text']}", styles["BodyText"]))

    story.append(Spacer(1, 12))

    add_heading(story, "Cons")
    con_rows = pros[pros["type"] == "con"]
    if con_rows.empty:
        story.append(Paragraph("No major weaknesses available.", styles["BodyText"]))
    else:
        for _, row in con_rows.iterrows():
            story.append(Paragraph(f"• {row['text']}", styles["BodyText"]))

    story.append(Spacer(1, 12))

    add_heading(story, "Cash Flow Intelligence")
    if not cash.empty:
        row = cash.iloc[0]
        story.append(Paragraph(
            f"CFO Quality: {row.get('cfo_quality_label','N/A')}",
            styles["BodyText"]))
        story.append(Paragraph(
            f"Capital Allocation: {row.get('capital_allocation_label','N/A')}",
            styles["BodyText"]))

    story.append(Spacer(1, 12))

    add_heading(story, "Capital Allocation Grade")
    if not allocation.empty:
        row = allocation.iloc[0]
        story.append(Paragraph(
            f"Allocation Style: {row.get('allocation_style','N/A')}",
            styles["BodyText"]))
        story.append(Paragraph(
            f"Grade: {row.get('grade','N/A')}",
            styles["BodyText"]))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "Generated by Nifty100 Financial Intelligence Platform",
        styles["Italic"]
    ))

    doc.build(story)
    print(f"Generated: {filename}")


def main():
    conn = sqlite3.connect(DB_PATH)
    companies = pd.read_sql("SELECT id FROM companies", conn)
    conn.close()

    generate_pdf(companies.iloc[0]["id"])


if __name__ == "__main__":
    main()
